name: 'Next Semver Release Draft'
description: 'Creates a draft release with next semver tag'
author: 'Chris Kerins'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  commitish:
    description: 'Release target. Default: `main` branch'
    required: false
  bump:
    description: 'Semver bump type. Options: major, minor, patch, prerelease. Default: patch.'
    required: false
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'save'
  color: 'blue'