name: 'Next Semver Release Draft'
description: 'Creates a draft release with next semver tag'
author: 'Chris Kerins'
inputs:

  commitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: `main` branch'
    required: false
  owner:
    description: 'Owner of the repository if it is not the current one'
    required: false
  repo:
    description: 'Repository on which to release.  Used only if you want to create the release on another repo'
    required: false
outputs:
  id:
    description: 'The ID of the created Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'