name: 'Chris Kerins'
description: 'Creates a draft release with next semver tag'
author: 'Chris Kerins'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
