name: 'CI'
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
      types: [published]

jobs:
  Lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Lint & Format
        run: 'npm run lint && npm run format'

  Test-Unit:
    name: Test - Unit
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Test
        run: 'npm run test'

  Build:
    name: Build
    runs-on: ubuntu-latest
    needs: [Lint, Test-Unit]
    steps:
      - name: Print GitHub event action
        run: |
          echo "${{ github.event.action }}"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci --no-progress --ignore-scripts=false
      
      - name: Build
        run: 'npm run build && npm run package'
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: ${{ github.token }}

