name: Dependabot Pull Request Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: Worthy-Cause/shared-workflows/.github/workflows/dependabot-automerge.yml@v1.0.0

